### ISSUE TITLE
how to install via composer?

### ISSUE THREAD

**Issue by mrattilakovacs** [mightyforms/mightyforms-magento-plugin#1]

**Comment by mrattilakovacs** [comment]
.

**Comment by OleksandrLysyi** [comment]
In case you chose installation via Composer, you need to:

1. Go to Magento root folder, like a cd /var/www/html
2. Run `composer require mightyforms/mightyforms:1.0.8`  where 1.0.8 - it's a version of extension.
3. Now, let's check is MightyForms extension was installed in your store:  run `php bin/magento module:status` to see which extensions is enabled or disabled. [screenshot](https://downloads.intercomcdn.com/i/o/300999574/5a2629755edb6ab6e536ba53/Screenshot_3.png)
4. As we can see, Porthas_MightyForms is [disabled](https://downloads.intercomcdn.com/i/o/301000221/8cf8dff2f227004b990cf898/image.jpg). To enable it run: `php bin/magento module:enable Porthas_MightyForms`

And as a final step, run next commands: 
`php bin/magento setup:upgrade`
`php bin/magento cache:flush`
 

Detailed explanation of the process you can find in Magento [acticle](https://devdocs.magento.com/cloud/howtos/install-components.html)
